### ISSUE TITLE
Touchpad doesn't function after installation

### ISSUE THREAD

**Issue by bryfur** [aarch64-laptops/debian-cdimage#3]
I followed the installation guide on my C630. After installation the touchpad doesn't seem to function. Is this currently expected? 

Thank you for your work on this.

**Comment by shawnguo2** [comment]
@BryanF0 No, this is not expected.  Touchpad should work, and at least it works in my testing.  Can you run the installation USB disk again with `Graphical Install` option to see if touchpad work in there?

**Comment by bryfur** [comment]
Yes the touchpad worked during the Graphical Install.

**Comment by shawnguo2** [comment]
Thanks, so the hardware is good :) Do you see `Touchpad` in `evtest` input device list?  Mine looks like - https://pastebin.com/raw/Na0ZJsF8

**Comment by shawnguo2** [comment]
@BryanF0 The cause of the issue has been identified, and we will fix it in the v0.3 CD image.  You can download the DTB below, put it into `/boot/efi/dtb/` and reboot machine to get your touchpad work.

https://fileserver.linaro.org/s/DszRa9HGKAMJddA

**Comment by powderluv** [comment]
confirmed this solution works on my c630

**Comment by bryfur** [comment]
Just installed v0.3. Working now. Overall this is very usable on the c630. Thank you.
