### ISSUE TITLE
Can't reinstall

### ISSUE THREAD

**Issue by Drinkingpants74** [aarch64-laptops/debian-cdimage#5]
I semi-broke my Debian install and decided to reinstall to fix the issues. However, the DTBLoader is keeping me from reinstalling Debian. When I select "Install" in the menu, it says "DT in use - unregistering ACPI tables", then loops back into the Debian Installer selection screen.

**Comment by shawnguo2** [comment]
Yes, this is something we need to fix in the next release.  There is some problem in booting 5.10 kernel with 5.11 DTB.  You can work around the issue by disabling DtbLoader for now in either way below.

* If you have access to `/boot/efi` folder, remove file `DtbLoader.efi` or folder `dtb` from there.
* Launch UEFI Shell and run `bcfg driver rm 0` to remove DtbLoader invoking from UEFI.

**Comment by Drinkingpants74** [comment]
I don't know what went wrong, but I can't boot the Debian image off a USB anymore. I can only boot the Ubuntu Preinstalled image. Is there a way to access grub through that one?

**Comment by shawnguo2** [comment]
Sorry, I do not follow.  Are you saying you cannot boot the laptop off the Debian install USB disk any more? the same USB disk that worked for you with the last Debian install?

**Comment by Drinkingpants74** [comment]
Yes. The only thing that boots anymore is the Ubuntu Preinstall image. The Debian image doesn't even show up as an option when it's plugged in. I've tried multiple flash drives and both ports as well to rule out either of them being faulty.

**Comment by shawnguo2** [comment]
This is very odd, and it's not the issue you were reporting here initially. Have you done anything in the middle? I do not know anything that could break boot of Debian USB disk, except a broken USB disk or UEFI Secure Boot being enabled.  Also, is Ubuntu Preinstall image you mean the Ubuntu Live CD image on USB disk, or Ubuntu installed on main disk?

**Comment by Drinkingpants74** [comment]
I had gotten into Windows after the original comment and I removed Debian from the disk so I could reinstall it. My logic was if I removed the Debian install, it would remove the DtbLoader and I could reinstall like I did earlier. When I rebooted the USB option was gone, except for the Ubuntu image. The Ubuntu image I'm talking about is the one from [aarch64-laptops/builds](https://github.com/aarch64-laptops/build).

**Comment by shawnguo2** [comment]
Are you running Lenovo Yoga C630 laptop?  On this laptop, you do not need to press any Fn key and select boot option to get boot from USB disk.  All you need to do is plug in the installer USB disk.  Can you describe how you boot from USB disk in details, and attach some boot screen pictures?  I do not understand what you said about `USB option was gone`.

**Comment by Drinkingpants74** [comment]
I am using the Lenovo Yoga C630.  I enter the boot menu by pressing F12 so that way I can be certain it will boot into the correct device. If I plug in the Debian USB, and don't select anything it boots directly into Grub Rescue.

In the pictures below, the first picture has the Ubuntu image on the USB, and the second has the Debian image on it.

![IMG_20210126_125817](https://user-images.githubusercontent.com/60319968/105885158-c0f73a80-5fd6-11eb-9492-e08d393ed389.jpg)

![IMG_20210126_123540](https://user-images.githubusercontent.com/60319968/105885152-bf2d7700-5fd6-11eb-891a-2f1a9a4e5f7a.jpg)

**Comment by shawnguo2** [comment]
It looks really like that the Debian USB disk is the cause.  Have you done anything to the USB disk that worked for you last time? Can you double check there is a valid EFI partition on the USB disk with expected files?  I attached mine here for your reference.
```
$ sudo fdisk -l /dev/sde
Disk /dev/sde: 28.7 GiB, 30765219840 bytes, 60088320 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot   Start     End Sectors  Size Id Type
/dev/sde1             0 1421311 1421312  694M 83 Linux
/dev/sde2       1421312 1425407    4096    2M ef EFI (FAT-12/16/32)
$ sudo mount /dev/sde2 mnt/
$ tree mnt/
mnt/
└── efi
    ├── boot
    │   └── bootaa64.efi
    └── shell
        └── Shell.efi

3 directories, 2 files
```

**Comment by Drinkingpants74** [comment]
So I ran those commands last night and everything matched up and was fine. I then plugged the USB in my laptop to try booting from it again and it didn't see it as usual. It was late so I went to bed, then I reran the commands on the USB this morning and I got this:

>$ sudo fdisk -l /dev/sda
Disk /dev/sda: 14.32 GiB, 15376318464 bytes, 30031872 sectors
Disk model: Cruzer Glide    
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 95DE1481-DA0D-488B-ABD2-FA91FA8D536E

>Device     Start     End Sectors   Size Type
/dev/sda1      0 1801599 1801600 879.7M Microsoft basic data
/dev/sda2    964    5891    4928   2.4M Microsoft basic data

The drive is still labeled as "Debian Unstable ARM64 1", but for some reason the formatting changed when I plugged it in. The even weirder part is that when I try to mount the drive using the command, it gives me this error:

>$ sudo mount /dev/sda2 /media
mount: /media: wrong fs type, bad option, bad superblock on /dev/sda2, missing codepage or helper program, or other error.

I've tried this multiple times and it does the same thing. The USB looks fine upon initial writing, then after it gets plugged into the laptop it gets corrupted.

**Comment by shawnguo2** [comment]
So looks like you need to "fix" the USB key or find a new one to test.

**Comment by Drinkingpants74** [comment]
After trying both of my flash drives, I ordered another flash drive to see if that might make a difference. It arrived this afternoon, and I was able to boot from the new USB. I removed DTB and reinstalled Debian and everything seems to be working fine. Thanks for the help.
