### ISSUE TITLE
Image does not install on the Samsung book 2 

### ISSUE THREAD

**Issue by finkegabriel** [aarch64-laptops/debian-cdimage#8]
Hello, I have a Samsung book 2 with the Qualcomm Snapdragon 850 processor. I have been able to drop down into a shell and fs5 mode. From the GRUB screen after I hit enter on Install this is the screen I receive. 

![PXL_20210202_170401935](https://user-images.githubusercontent.com/40010444/106636211-ef2ccb00-653e-11eb-8e65-91a95f0ae8b1.jpg)

**Comment by shawnguo2** [comment]
First of all, the installer was only tested on Lenovo Yoga C630.  Secondly, I can see nothing on the picture of screen.  You can try to  press `e` in GRUB screen and remove `quiet` from `linux` line, so that you can get messages on kernel boot.
